- name: Install MySQL Database
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - mariadb-server
    - mariadb

- name: Install PyMySQL
  pip:
    name: PyMySQL
    state: present

- name: Start MySQL Service
  service: 
    name: mariadb
    state: started
    enabled: yes

- name: Create Application Database
  mysql_db: 
    name: '{{ db_name }}'
    state: present

- name: Create Application DB User
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: Create table in the DB and an entry to it
  community.mysql.mysql_query: 
    login_db: '{{ db_name }}'
    query:
      - CREATE TABLE employees (name VARCHAR(20));
      - INSERT INTO employees VALUES('ISAI')